{
 "title": "Elixir Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(route) (increase(router_dispatch_stop_count{route!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by(route) (delta(router_dispatch_stop_sum{route!=\"/metrics\"}[1m])) / 1000000 /sum by(route) (increase(router_dispatch_stop_count{route!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (increase(router_dispatch_stop_count{route!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (increase(router_dispatch_stop_count{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (increase(router_dispatch_stop_count{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Outgoing Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(host, path) (delta(finch_request_stop_sum[1m])) / 1000000 / sum by(host, path) (increase(finch_request_stop_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Outgoing error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by(host, path, status) (increase(finch_request_stop_count{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host, path, status) (increase(finch_request_stop_count{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host, path, status) (increase(finch_request_stop_count{status=\"0\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "sum by(query)(delta(repo_query_sum[1m]))/1000000 / sum by(query)(increase(repo_query_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{filename=\"/tmp/log/observability-elixir.log\"} |= ``"
    }
   ]
  }
 ]
}